### ISSUE TITLE
Idea: Adafruit BME280 and i2c address 0x77

### ISSUE THREAD

**Issue by barning** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#16]
The Adafruit BME280 uses i2c address 0x77 by default and must be manually set to 0x76 with a jumper, or the weather steation won't work. I knew the problem and the solution, but maybe you should also scan for 0x77.
Great project and thanks a lot!

**Comment by HomeKidd** [comment]
Hi! 
Sorry for the late answer but I've totally forget to reply 😓😅
I have this issue open until i can add this feature.
The main reason why I've never added the multiple i2c bus address support is because the small CJMCU board is required for the [PCB design](https://github.com/HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve/wiki/PCB-Design), also its much cheaper and smaller than the Adafruit one. FYI the default address for BMx280 is always 0x76. 😄

**Comment by barning** [comment]
No problem. I just noticed this and thought this could be frustrate someone, who has the Adafruit one lying around and don't know this.
