### ISSUE TITLE
devices not found

### ISSUE THREAD

**Issue by tibur79** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#18]
day after several attempts with both main.bin and otaboot I can't connect the device to homekit I tried various parameters like 0x0000 0x1000 0x2000 dio qio both with d1mini and
AZDelivery NodeMCU ESP8266 ESP-12F WiFi Lua Lolin V3 the problem remains with ota from the iphone settings makes you connect to lcm ... but then nothing even after 20 minutes of waiting does nothing with main immediately starts flashing the devices but from settings do not see what could be iphone with ios 13.6.1 thanks

**Comment by HomeKidd** [comment]
Hi!

Sadly the OTA part is not my code, it was made by [HomeACcessoryKid](https://github.com/HomeACcessoryKid)! OTA downloading process is very buggy, takes at least 7 minutes to download the firmware, also it very often fails downloading it.

Without OTA it should work! Simply just erase the flash and upload the main.bin instead of otaboot.bin as mentioned in the [Wiki](https://github.com/HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve/wiki/Build-Instructions#installation-without-ota)!
If you want to update the firmware you can simply flash the newest main.bin **without erasing the flash**. Every setting should be kept 😄

>  immediately starts flashing the devices

Did you connected the OLED and BME280 before? Without any connected sensor it wont start properly...

Also others reported similar issues that has been solved. #14 , #8 , #5

**Comment by tibur79** [comment]
thanks for the help but i'm trying them all and for now nothing even with the monitor r sensor connected

**Comment by HomeKidd** [comment]
Could you send me logs using serial monitor what is happening when you start the device?

**Comment by tibur79** [comment]
![AE9AF77D-0C64-4C67-A726-C71425FBD0D6_1_105_c](https://user-images.githubusercontent.com/47913372/90389723-62727b80-e08a-11ea-92e7-3c38b3925fac.jpeg)
![22ADBF42-ABFE-41FA-A9E6-C1FEEABC1D57_1_105_c](https://user-images.githubusercontent.com/47913372/90389782-77e7a580-e08a-11ea-8ac8-d34fc8225f28.jpeg)

**Comment by HomeKidd** [comment]
I'm interested in the LOG files from the ESP itself (using Arduino's serial monitor)
![](https://circuits4you.com/wp-content/uploads/2016/12/ESP8266-Serial-Communication.png)

Or using [MacOS Terminal](https://apple.stackexchange.com/questions/32834/is-there-an-os-x-terminal-program-that-can-access-serial-ports)!

**Comment by tibur79** [comment]
how is the command

**Comment by HomeKidd** [comment]
> Or using [MacOS Terminal](https://apple.stackexchange.com/questions/32834/is-there-an-os-x-terminal-program-that-can-access-serial-ports)!

`screen /dev/<your-USB-port> 115200`

**Comment by tibur79** [comment]
I send the command but it says screen finished and does nothing sorry

**Comment by HomeKidd** [comment]
You can run `ls /dev/{tty,cu}.*` in Terminal _(which will list all the USB devices)_ and then `screen /dev/tty.usbserial-A800e3ZL 115200`
It worked for me!

Other ( and best way) is to use [Arduino](https://arduino-esp8266.readthedocs.io/en/latest/installing.html) to capture serial logs.

Also you can search for any [Serial application](https://pbxbook.com/other/mac-ser.html) for macOS

**Comment by tibur79** [comment]
broken monitor

**Comment by tibur79** [comment]
monitor rotto
