### ISSUE TITLE
GPIOs change

### ISSUE THREAD

**Issue by straubus** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#6]
Hi, is there any chance to change GPIOs between wemos and BME sensor, so I can plug it directly to board? BME supports 5v, so I want to be able to connect:
5v <-> VIN;    G <-> GND;    D4 <-> SCL;   D3 <-> SDA

**Comment by HomeKidd** [comment]
Hi!

**In short: Sorry I don't want to change the GPIO layout**, please use 3.3V and the preferred layout in [wiki](https://github.com/HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve/wiki/Hardware-setup#schematic)!

According to [Wemos pinout](https://escapequotes.net/wp-content/uploads/2016/02/esp8266-wemos-d1-mini-pinout.png) GPIO4 and 5 reserved for I2C Bus communication (and GPIO13-14 for secondary bus) Also D3 pin in the code is reserved for button input _(reset / screen power)_, but the biggest problem D3 pin is GPIO0 and with any sensor attached to it may cause booting problems because GPIO0 switches between [program download / boot](https://wiki.ai-thinker.com/_media/esp8266/a014ps01.pdf).
Another reason why I'm not planning to change the GPIO layout is because not everybody using only Wemos/NodeMCUs. 
Theres one more problem with 5V: BME runs on 3.3V _(it has a 5V to 3.3V regulator on the PCB)_.
BUT the logic level of the I2C will be 5V when the module powered via 5V. This isn't a problem with Wemos/NodeMCU because these have onboard logic level converters for these pins too but it may cause problems for others.  😄
