### ISSUE TITLE
Share main code

### ISSUE THREAD

**Issue by AchimPieters** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#9]
Why don't you share the main code?

**Comment by Kristian8606** [comment]
I would like to contribute to the development of Elgato eve history.  Would you share the code to figure out how to implement these features.

**Comment by HomeKidd** [comment]
I can't upload the main code because i'm running a custom modified version of esp-open-rtos, esp-homekit and a tons of modules are custom too (esp-wifi-config etc.). 99% of the people not able to compile my code, sorry.
If you are interested in Elgato Eve Characteristics you can find every information [here](https://github.com/simont77/fakegato-history/wiki/Elgato-Eve-History-Protocol)! 😄 

@Kristian8606 Even Maxim not implemented homekit [data type](https://github.com/maximkulkin/esp-homekit/branches) fully. Since december its still not working as it should be but he is working on that! Without HomeKit Data type it will not work at all.... also there are a lot of other problems with Eve data too...
